// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using senai_inlock_webAPI_CodeFirst.Contexts;

namespace senai_inlock_webAPI_CodeFirst.Migrations
{
    [DbContext(typeof(InLockContext))]
    [Migration("20210423190124_criacao-banco")]
    partial class criacaobanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("senai_inlock_webAPI_CodeFirst.Domains.Estudio", b =>
                {
                    b.Property<int>("idEstudio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nomeEstudio")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idEstudio");

                    b.ToTable("estudios");

                    b.HasData(
                        new
                        {
                            idEstudio = 1,
                            nomeEstudio = "Blizzard"
                        },
                        new
                        {
                            idEstudio = 2,
                            nomeEstudio = "Rockstar Studios"
                        },
                        new
                        {
                            idEstudio = 3,
                            nomeEstudio = "Square Enix"
                        });
                });

            modelBuilder.Entity("senai_inlock_webAPI_CodeFirst.Domains.Jogo", b =>
                {
                    b.Property<int>("idJogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dataLancamento")
                        .HasColumnType("DATE");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("idEstudio")
                        .HasColumnType("int");

                    b.Property<string>("nomeJogo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<decimal>("valor")
                        .HasColumnType("DECIMAL (18,2)");

                    b.HasKey("idJogo");

                    b.HasIndex("idEstudio");

                    b.ToTable("jogos");

                    b.HasData(
                        new
                        {
                            idJogo = 1,
                            dataLancamento = new DateTime(2012, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            descricao = "É um jogo que contém bastante ação...",
                            idEstudio = 1,
                            nomeJogo = "Diablo 3",
                            valor = 99.00m
                        },
                        new
                        {
                            idJogo = 2,
                            dataLancamento = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            descricao = "Jogo eletrônico de ação-aventura western.",
                            idEstudio = 1,
                            nomeJogo = "Red Dead Redemption II",
                            valor = 99.00m
                        });
                });

            modelBuilder.Entity("senai_inlock_webAPI_CodeFirst.Domains.TipoUsuario", b =>
                {
                    b.Property<int>("idTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("permissao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("idTipoUsuario");

                    b.ToTable("tipoUsuarios");

                    b.HasData(
                        new
                        {
                            idTipoUsuario = 1,
                            permissao = "Administrador"
                        },
                        new
                        {
                            idTipoUsuario = 2,
                            permissao = "Cliente"
                        });
                });

            modelBuilder.Entity("senai_inlock_webAPI_CodeFirst.Domains.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<int>("idTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idUsuario");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("idTipoUsuario");

                    b.ToTable("usuarios");

                    b.HasData(
                        new
                        {
                            idUsuario = 1,
                            email = "admin@admin.com",
                            idTipoUsuario = 1,
                            senha = "admin"
                        },
                        new
                        {
                            idUsuario = 2,
                            email = "cliente@cliente.com",
                            idTipoUsuario = 2,
                            senha = "cliente"
                        });
                });

            modelBuilder.Entity("senai_inlock_webAPI_CodeFirst.Domains.Jogo", b =>
                {
                    b.HasOne("senai_inlock_webAPI_CodeFirst.Domains.Estudio", "estudio")
                        .WithMany("jogos")
                        .HasForeignKey("idEstudio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estudio");
                });

            modelBuilder.Entity("senai_inlock_webAPI_CodeFirst.Domains.Usuario", b =>
                {
                    b.HasOne("senai_inlock_webAPI_CodeFirst.Domains.TipoUsuario", "tipoUsuario")
                        .WithMany()
                        .HasForeignKey("idTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoUsuario");
                });

            modelBuilder.Entity("senai_inlock_webAPI_CodeFirst.Domains.Estudio", b =>
                {
                    b.Navigation("jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
